# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0cpractice.rpc\x1a google/protobuf/descriptor.proto\".\n\x0cWifiSettings\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x18\n\nLedRequest\x12\n\n\x02on\x18\x01 \x01(\x08\"\r\n\x0bLedResponse\"\x1a\n\x0b\x45\x63hoRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1b\n\x0c\x45\x63hoResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\" \n\x11\x45\x63hoRequestMalloc\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\"!\n\x12\x45\x63hoResponseMalloc\x12\x0b\n\x03msg\x18\x01 \x01(\x0c\"\x0f\n\rSensorRequest\"O\n\x0fSensorTelemetry\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02:\x15\x8a\xb5\x18\x11/telemetry/sensor\"\x07\n\x05\x45mpty2\xa5\x03\n\rDeviceService\x12=\n\x06SetLed\x12\x18.practice.rpc.LedRequest\x1a\x19.practice.rpc.LedResponse\x12=\n\x04\x45\x63ho\x12\x19.practice.rpc.EchoRequest\x1a\x1a.practice.rpc.EchoResponse\x12O\n\nEchoMalloc\x12\x1f.practice.rpc.EchoRequestMalloc\x1a .practice.rpc.EchoResponseMalloc\x12\x45\n\x11StartSensorStream\x12\x1b.practice.rpc.SensorRequest\x1a\x13.practice.rpc.Empty\x12<\n\x10StopSensorStream\x12\x13.practice.rpc.Empty\x1a\x13.practice.rpc.Empty\x12@\n\rConfigureWifi\x12\x1a.practice.rpc.WifiSettings\x1a\x13.practice.rpc.Empty:4\n\tzenoh_key\x12\x1f.google.protobuf.MessageOptions\x18\xd1\x86\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORTELEMETRY']._loaded_options = None
  _globals['_SENSORTELEMETRY']._serialized_options = b'\212\265\030\021/telemetry/sensor'
  _globals['_WIFISETTINGS']._serialized_start=65
  _globals['_WIFISETTINGS']._serialized_end=111
  _globals['_LEDREQUEST']._serialized_start=113
  _globals['_LEDREQUEST']._serialized_end=137
  _globals['_LEDRESPONSE']._serialized_start=139
  _globals['_LEDRESPONSE']._serialized_end=152
  _globals['_ECHOREQUEST']._serialized_start=154
  _globals['_ECHOREQUEST']._serialized_end=180
  _globals['_ECHORESPONSE']._serialized_start=182
  _globals['_ECHORESPONSE']._serialized_end=209
  _globals['_ECHOREQUESTMALLOC']._serialized_start=211
  _globals['_ECHOREQUESTMALLOC']._serialized_end=243
  _globals['_ECHORESPONSEMALLOC']._serialized_start=245
  _globals['_ECHORESPONSEMALLOC']._serialized_end=278
  _globals['_SENSORREQUEST']._serialized_start=280
  _globals['_SENSORREQUEST']._serialized_end=295
  _globals['_SENSORTELEMETRY']._serialized_start=297
  _globals['_SENSORTELEMETRY']._serialized_end=376
  _globals['_EMPTY']._serialized_start=378
  _globals['_EMPTY']._serialized_end=385
  _globals['_DEVICESERVICE']._serialized_start=388
  _globals['_DEVICESERVICE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
