/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PRACTICE_RPC_SERVICE_PB_H_INCLUDED
#define PB_PRACTICE_RPC_SERVICE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _practice_rpc_WifiSettings {
    char ssid[32];
    char password[64];
} practice_rpc_WifiSettings;

typedef struct _practice_rpc_LedRequest {
    bool on;
} practice_rpc_LedRequest;

typedef struct _practice_rpc_LedResponse {
    char dummy_field;
} practice_rpc_LedResponse;

typedef struct _practice_rpc_EchoRequest {
    char msg[128];
} practice_rpc_EchoRequest;

typedef struct _practice_rpc_EchoResponse {
    char msg[128];
} practice_rpc_EchoResponse;

typedef struct _practice_rpc_EchoRequestMalloc {
    pb_bytes_array_t *msg;
} practice_rpc_EchoRequestMalloc;

typedef struct _practice_rpc_EchoResponseMalloc {
    pb_bytes_array_t *msg;
} practice_rpc_EchoResponseMalloc;

typedef struct _practice_rpc_SensorRequest {
    char dummy_field;
} practice_rpc_SensorRequest;

typedef struct _practice_rpc_SensorTelemetry {
    float temperature;
    float humidity;
} practice_rpc_SensorTelemetry;

typedef struct _practice_rpc_Empty {
    char dummy_field;
} practice_rpc_Empty;


/* Extensions */
/* Extension field practice_rpc_zenoh_key was skipped because only "optional"
   type of extension fields is currently supported. */

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define practice_rpc_WifiSettings_init_default   {"", ""}
#define practice_rpc_LedRequest_init_default     {0}
#define practice_rpc_LedResponse_init_default    {0}
#define practice_rpc_EchoRequest_init_default    {""}
#define practice_rpc_EchoResponse_init_default   {""}
#define practice_rpc_EchoRequestMalloc_init_default {NULL}
#define practice_rpc_EchoResponseMalloc_init_default {NULL}
#define practice_rpc_SensorRequest_init_default  {0}
#define practice_rpc_SensorTelemetry_init_default {0, 0}
#define practice_rpc_Empty_init_default          {0}
#define practice_rpc_WifiSettings_init_zero      {"", ""}
#define practice_rpc_LedRequest_init_zero        {0}
#define practice_rpc_LedResponse_init_zero       {0}
#define practice_rpc_EchoRequest_init_zero       {""}
#define practice_rpc_EchoResponse_init_zero      {""}
#define practice_rpc_EchoRequestMalloc_init_zero {NULL}
#define practice_rpc_EchoResponseMalloc_init_zero {NULL}
#define practice_rpc_SensorRequest_init_zero     {0}
#define practice_rpc_SensorTelemetry_init_zero   {0, 0}
#define practice_rpc_Empty_init_zero             {0}

/* Field tags (for use in manual encoding/decoding) */
#define practice_rpc_WifiSettings_ssid_tag       1
#define practice_rpc_WifiSettings_password_tag   2
#define practice_rpc_LedRequest_on_tag           1
#define practice_rpc_EchoRequest_msg_tag         1
#define practice_rpc_EchoResponse_msg_tag        1
#define practice_rpc_EchoRequestMalloc_msg_tag   1
#define practice_rpc_EchoResponseMalloc_msg_tag  1
#define practice_rpc_SensorTelemetry_temperature_tag 1
#define practice_rpc_SensorTelemetry_humidity_tag 2
#define practice_rpc_zenoh_key_tag               50001

/* Struct field encoding specification for nanopb */
#define practice_rpc_WifiSettings_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              1) \
X(a, STATIC,   SINGULAR, STRING,   password,          2)
#define practice_rpc_WifiSettings_CALLBACK NULL
#define practice_rpc_WifiSettings_DEFAULT NULL

#define practice_rpc_LedRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     on,                1)
#define practice_rpc_LedRequest_CALLBACK NULL
#define practice_rpc_LedRequest_DEFAULT NULL

#define practice_rpc_LedResponse_FIELDLIST(X, a) \

#define practice_rpc_LedResponse_CALLBACK NULL
#define practice_rpc_LedResponse_DEFAULT NULL

#define practice_rpc_EchoRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   msg,               1)
#define practice_rpc_EchoRequest_CALLBACK NULL
#define practice_rpc_EchoRequest_DEFAULT NULL

#define practice_rpc_EchoResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   msg,               1)
#define practice_rpc_EchoResponse_CALLBACK NULL
#define practice_rpc_EchoResponse_DEFAULT NULL

#define practice_rpc_EchoRequestMalloc_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, BYTES,    msg,               1)
#define practice_rpc_EchoRequestMalloc_CALLBACK NULL
#define practice_rpc_EchoRequestMalloc_DEFAULT NULL

#define practice_rpc_EchoResponseMalloc_FIELDLIST(X, a) \
X(a, POINTER,  SINGULAR, BYTES,    msg,               1)
#define practice_rpc_EchoResponseMalloc_CALLBACK NULL
#define practice_rpc_EchoResponseMalloc_DEFAULT NULL

#define practice_rpc_SensorRequest_FIELDLIST(X, a) \

#define practice_rpc_SensorRequest_CALLBACK NULL
#define practice_rpc_SensorRequest_DEFAULT NULL

#define practice_rpc_SensorTelemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       1) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          2)
#define practice_rpc_SensorTelemetry_CALLBACK NULL
#define practice_rpc_SensorTelemetry_DEFAULT NULL

#define practice_rpc_Empty_FIELDLIST(X, a) \

#define practice_rpc_Empty_CALLBACK NULL
#define practice_rpc_Empty_DEFAULT NULL

extern const pb_msgdesc_t practice_rpc_WifiSettings_msg;
extern const pb_msgdesc_t practice_rpc_LedRequest_msg;
extern const pb_msgdesc_t practice_rpc_LedResponse_msg;
extern const pb_msgdesc_t practice_rpc_EchoRequest_msg;
extern const pb_msgdesc_t practice_rpc_EchoResponse_msg;
extern const pb_msgdesc_t practice_rpc_EchoRequestMalloc_msg;
extern const pb_msgdesc_t practice_rpc_EchoResponseMalloc_msg;
extern const pb_msgdesc_t practice_rpc_SensorRequest_msg;
extern const pb_msgdesc_t practice_rpc_SensorTelemetry_msg;
extern const pb_msgdesc_t practice_rpc_Empty_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define practice_rpc_WifiSettings_fields &practice_rpc_WifiSettings_msg
#define practice_rpc_LedRequest_fields &practice_rpc_LedRequest_msg
#define practice_rpc_LedResponse_fields &practice_rpc_LedResponse_msg
#define practice_rpc_EchoRequest_fields &practice_rpc_EchoRequest_msg
#define practice_rpc_EchoResponse_fields &practice_rpc_EchoResponse_msg
#define practice_rpc_EchoRequestMalloc_fields &practice_rpc_EchoRequestMalloc_msg
#define practice_rpc_EchoResponseMalloc_fields &practice_rpc_EchoResponseMalloc_msg
#define practice_rpc_SensorRequest_fields &practice_rpc_SensorRequest_msg
#define practice_rpc_SensorTelemetry_fields &practice_rpc_SensorTelemetry_msg
#define practice_rpc_Empty_fields &practice_rpc_Empty_msg

/* Maximum encoded size of messages (where known) */
/* practice_rpc_EchoRequestMalloc_size depends on runtime parameters */
/* practice_rpc_EchoResponseMalloc_size depends on runtime parameters */
#define PRACTICE_RPC_SERVICE_PB_H_MAX_SIZE       practice_rpc_EchoRequest_size
#define practice_rpc_EchoRequest_size            130
#define practice_rpc_EchoResponse_size           130
#define practice_rpc_Empty_size                  0
#define practice_rpc_LedRequest_size             2
#define practice_rpc_LedResponse_size            0
#define practice_rpc_SensorRequest_size          0
#define practice_rpc_SensorTelemetry_size        10
#define practice_rpc_WifiSettings_size           98

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
