/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "service.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(practice_rpc_WifiSettings, practice_rpc_WifiSettings, AUTO)


PB_BIND(practice_rpc_LedRequest, practice_rpc_LedRequest, AUTO)


PB_BIND(practice_rpc_LedResponse, practice_rpc_LedResponse, AUTO)


PB_BIND(practice_rpc_EchoRequest, practice_rpc_EchoRequest, AUTO)


PB_BIND(practice_rpc_EchoResponse, practice_rpc_EchoResponse, AUTO)


PB_BIND(practice_rpc_EchoRequestMalloc, practice_rpc_EchoRequestMalloc, AUTO)


PB_BIND(practice_rpc_EchoResponseMalloc, practice_rpc_EchoResponseMalloc, AUTO)


PB_BIND(practice_rpc_SensorRequest, practice_rpc_SensorRequest, AUTO)


PB_BIND(practice_rpc_SensorTelemetry, practice_rpc_SensorTelemetry, AUTO)


PB_BIND(practice_rpc_Empty, practice_rpc_Empty, AUTO)




